namespace Submarine {
	
	public struct LanguageInfo {
		public string long_code { get; private set; }
		public string? short_code { get; private set; }
		public string name { get; private set; }
		
		public LanguageInfo(string long_code, string short_code, string name) {
			this.long_code = long_code;
			this.short_code = short_code;
			this.name = name;
		}
	}
	
	private Gee.List<string> all_language_codes = null;
	private Gee.Map<string, LanguageInfo?> language_infos = null;
	
	public Gee.List<string> get_language_codes() {
		if(all_language_codes == null) {
			all_language_codes = new Gee.ArrayList<string>();
			for(int i=0; i<LANGUAGE_INFOS_ARRAY.length; i++) {
				var language_info = LANGUAGE_INFOS_ARRAY[i];
				all_language_codes.add(language_info.long_code);
				if(language_info.short_code != null) {
					all_language_codes.add(language_info.short_code);
				}
			}
			all_language_codes.sort( (a, b) => {return ((string)a).ascii_casecmp((string)b);} );
		}
		
		return all_language_codes.read_only_view;
	}
	
	public LanguageInfo? get_language_info(string language_code) {
		if(language_infos == null) {
			language_infos = new Gee.HashMap<string, LanguageInfo?>();
			for(int i=0; i<LANGUAGE_INFOS_ARRAY.length; i++) {
				var language_info = LANGUAGE_INFOS_ARRAY[i];
				language_infos.set(language_info.long_code, language_info);
				if(language_info.short_code != null) {
					language_infos.set(language_info.short_code, language_info);
				}
			}
		}
		
		if(language_code in language_infos.keys) {
			return language_infos[language_code];
		}
		
		return null;
	}
	
	//parsed from http://www.loc.gov/standards/iso639-2/php/code_list.php
	private const LanguageInfo[] LANGUAGE_INFOS_ARRAY = {
		{"aar",	"aa",	"Afar"},
		{"abk",	"ab",	"Abkhazian"},
		{"ace",	null,	"Achinese"},
		{"ach",	null,	"Acoli"},
		{"ada",	null,	"Adangme"},
		{"ady",	null,	"Adyghe; Adygei"},
		{"afa",	null,	"Afro-Asiatic languages"},
		{"afh",	null,	"Afrihili"},
		{"afr",	"af",	"Afrikaans"},
		{"ain",	null,	"Ainu"},
		{"aka",	"ak",	"Akan"},
		{"akk",	null,	"Akkadian"},
		//{"alb (B)"},
		//{"sqi (T)",	"sq",	"Albanian"},
		{"alb",	"sq",	"Albanian"},
		{"sqi",	"sq",	"Albanian"},
		{"ale",	null,	"Aleut"},
		{"alg",	null,	"Algonquian languages"},
		{"alt",	null,	"Southern Altai"},
		{"amh",	"am",	"Amharic"},
		{"ang",	null,	"English, Old (ca.450-1100)"},
		{"anp",	null,	"Angika"},
		{"apa",	null,	"Apache languages"},
		{"ara",	"ar",	"Arabic"},
		{"arc",	null,	"Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"},
		{"arg",	"an",	"Aragonese"},
		//{"arm (B)"},
		//{"hye (T)",	"hy",	"Armenian"},
		{"arm",	"hy",	"Armenian"},
		{"hye",	"hy",	"Armenian"},
		{"arn",	null,	"Mapudungun; Mapuche"},
		{"arp",	null,	"Arapaho"},
		{"art",	null,	"Artificial languages"},
		{"arw",	null,	"Arawak"},
		{"asm",	"as",	"Assamese"},
		{"ast",	null,	"Asturian; Bable; Leonese; Asturleonese"},
		{"ath",	null,	"Athapascan languages"},
		{"aus",	null,	"Australian languages"},
		{"ava",	"av",	"Avaric"},
		{"ave",	"ae",	"Avestan"},
		{"awa",	null,	"Awadhi"},
		{"aym",	"ay",	"Aymara"},
		{"aze",	"az",	"Azerbaijani"},
		{"bad",	null,	"Banda languages"},
		{"bai",	null,	"Bamileke languages"},
		{"bak",	"ba",	"Bashkir"},
		{"bal",	null,	"Baluchi"},
		{"bam",	"bm",	"Bambara"},
		{"ban",	null,	"Balinese"},
		//{"baq (B)"},
		//{"eus (T)",	"eu",	"Basque"},
		{"baq",	"eu",	"Basque"},
		{"eus",	"eu",	"Basque"},
		{"bas",	null,	"Basa"},
		{"bat",	null,	"Baltic languages"},
		{"bej",	null,	"Beja; Bedawiyet"},
		{"bel",	"be",	"Belarusian"},
		{"bem",	null,	"Bemba"},
		{"ben",	"bn",	"Bengali"},
		{"ber",	null,	"Berber languages"},
		{"bho",	null,	"Bhojpuri"},
		{"bih",	"bh",	"Bihari languages"},
		{"bik",	null,	"Bikol"},
		{"bin",	null,	"Bini; Edo"},
		{"bis",	"bi",	"Bislama"},
		{"bla",	null,	"Siksika"},
		{"bnt",	null,	"Bantu languages"},
		//{"tib (B)"},
		//{"bod (T)",	"bo",	"Tibetan"},
		{"tib",	"bo",	"Tibetan"},
		{"bod",	"bo",	"Tibetan"},
		{"bos",	"bs",	"Bosnian"},
		{"bra",	null,	"Braj"},
		{"bre",	"br",	"Breton"},
		{"btk",	null,	"Batak languages"},
		{"bua",	null,	"Buriat"},
		{"bug",	null,	"Buginese"},
		{"bul",	"bg",	"Bulgarian"},
		//{"bur (B)"},
		//{"mya (T)",	"my",	"Burmese"},
		{"bur",	"my",	"Burmese"},
		{"mya",	"my",	"Burmese"},
		{"byn",	null,	"Blin; Bilin"},
		{"cad",	null,	"Caddo"},
		{"cai",	null,	"Central American Indian languages"},
		{"car",	null,	"Galibi Carib"},
		{"cat",	"ca",	"Catalan; Valencian"},
		{"cau",	null,	"Caucasian languages"},
		{"ceb",	null,	"Cebuano"},
		{"cel",	null,	"Celtic languages"},
		//{"cze (B)"},
		//{"ces (T)",	"cs",	"Czech"},
		{"cze",	"cs",	"Czech"},
		{"ces",	"cs",	"Czech"},
		{"cha",	"ch",	"Chamorro"},
		{"chb",	null,	"Chibcha"},
		{"che",	"ce",	"Chechen"},
		{"chg",	null,	"Chagatai"},
		//{"chi (B)"},
		//{"zho (T)",	"zh",	"Chinese"},
		{"chi",	"zh",	"Chinese"},
		{"zho",	"zh",	"Chinese"},
		{"chk",	null,	"Chuukese"},
		{"chm",	null,	"Mari"},
		{"chn",	null,	"Chinook jargon"},
		{"cho",	null,	"Choctaw"},
		{"chp",	null,	"Chipewyan; Dene Suline"},
		{"chr",	null,	"Cherokee"},
		{"chu",	"cu",	"Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
		{"chv",	"cv",	"Chuvash"},
		{"chy",	null,	"Cheyenne"},
		{"cmc",	null,	"Chamic languages"},
		{"cop",	null,	"Coptic"},
		{"cor",	"kw",	"Cornish"},
		{"cos",	"co",	"Corsican"},
		{"cpe",	null,	"Creoles and pidgins, English based"},
		{"cpf",	null,	"Creoles and pidgins, French-based"},
		{"cpp",	null,	"Creoles and pidgins, Portuguese-based"},
		{"cre",	"cr",	"Cree"},
		{"crh",	null,	"Crimean Tatar; Crimean Turkish"},
		{"crp",	null,	"Creoles and pidgins"},
		{"csb",	null,	"Kashubian"},
		{"cus",	null,	"Cushitic languages"},
		//{"wel (B)"},
		//{"cym (T)",	"cy",	"Welsh"},
		{"wel",	"cy",	"Welsh"},
		{"cym",	"cy",	"Welsh"},
		//{"cze (B)"},
		//{"ces (T)",	"cs",	"Czech"},
		{"cze",	"cs",	"Czech"},
		{"ces",	"cs",	"Czech"},
		{"dak",	null,	"Dakota"},
		{"dan",	"da",	"Danish"},
		{"dar",	null,	"Dargwa"},
		{"day",	null,	"Land Dayak languages"},
		{"del",	null,	"Delaware"},
		{"den",	null,	"Slave (Athapascan)"},
		//{"ger (B)"},
		//{"deu (T)",	"de",	"German"},
		{"ger",	"de",	"German"},
		{"deu",	"de",	"German"},
		{"dgr",	null,	"Dogrib"},
		{"din",	null,	"Dinka"},
		{"div",	"dv",	"Divehi; Dhivehi; Maldivian"},
		{"doi",	null,	"Dogri"},
		{"dra",	null,	"Dravidian languages"},
		{"dsb",	null,	"Lower Sorbian"},
		{"dua",	null,	"Duala"},
		{"dum",	null,	"Dutch, Middle (ca.1050-1350)"},
		//{"dut (B)"},
		//{"nld (T)",	"nl",	"Dutch; Flemish"},
		{"dut",	"nl",	"Dutch; Flemish"},
		{"nld",	"nl",	"Dutch; Flemish"},
		{"dyu",	null,	"Dyula"},
		{"dzo",	"dz",	"Dzongkha"},
		{"efi",	null,	"Efik"},
		{"egy",	null,	"Egyptian (Ancient)"},
		{"eka",	null,	"Ekajuk"},
		//{"gre (B)"},
		//{"ell (T)",	"el",	"Greek, Modern (1453-)"},
		{"gre",	"el",	"Greek, Modern (1453-)"},
		{"ell",	"el",	"Greek, Modern (1453-)"},
		{"elx",	null,	"Elamite"},
		{"eng",	"en",	"English"},
		{"enm",	null,	"English, Middle (1100-1500)"},
		{"epo",	"eo",	"Esperanto"},
		{"est",	"et",	"Estonian"},
		//{"baq (B)"},
		//{"eus (T)",	"eu",	"Basque"},
		{"baq",	"eu",	"Basque"},
		{"eus",	"eu",	"Basque"},
		{"ewe",	"ee",	"Ewe"},
		{"ewo",	null,	"Ewondo"},
		{"fan",	null,	"Fang"},
		{"fao",	"fo",	"Faroese"},
		//{"per (B)"},
		//{"fas (T)",	"fa",	"Persian"},
		{"per",	"fa",	"Persian"},
		{"fas",	"fa",	"Persian"},
		{"fat",	null,	"Fanti"},
		{"fij",	"fj",	"Fijian"},
		{"fil",	null,	"Filipino; Pilipino"},
		{"fin",	"fi",	"Finnish"},
		{"fiu",	null,	"Finno-Ugrian languages"},
		{"fon",	null,	"Fon"},
		//{"fre (B)"},
		//{"fra (T)",	"fr",	"French"},
		{"fre",	"fr",	"French"},
		{"fra",	"fr",	"French"},
		//{"fre (B)"},
		//{"fra (T)",	"fr",	"French"},
		{"fre",	"fr",	"French"},
		{"fra",	"fr",	"French"},
		{"frm",	null,	"French, Middle (ca.1400-1600)"},
		{"fro",	null,	"French, Old (842-ca.1400)"},
		{"frr",	null,	"Northern Frisian"},
		{"frs",	null,	"Eastern Frisian"},
		{"fry",	"fy",	"Western Frisian"},
		{"ful",	"ff",	"Fulah"},
		{"fur",	null,	"Friulian"},
		{"gaa",	null,	"Ga"},
		{"gay",	null,	"Gayo"},
		{"gba",	null,	"Gbaya"},
		{"gem",	null,	"Germanic languages"},
		//{"geo (B)"},
		//{"kat (T)",	"ka",	"Georgian"},
		{"geo",	"ka",	"Georgian"},
		{"kat",	"ka",	"Georgian"},
		//{"ger (B)"},
		//{"deu (T)",	"de",	"German"},
		{"ger",	"de",	"German"},
		{"deu",	"de",	"German"},
		{"gez",	null,	"Geez"},
		{"gil",	null,	"Gilbertese"},
		{"gla",	"gd",	"Gaelic; Scottish Gaelic"},
		{"gle",	"ga",	"Irish"},
		{"glg",	"gl",	"Galician"},
		{"glv",	"gv",	"Manx"},
		{"gmh",	null,	"German, Middle High (ca.1050-1500)"},
		{"goh",	null,	"German, Old High (ca.750-1050)"},
		{"gon",	null,	"Gondi"},
		{"gor",	null,	"Gorontalo"},
		{"got",	null,	"Gothic"},
		{"grb",	null,	"Grebo"},
		{"grc",	null,	"Greek, Ancient (to 1453)"},
		//{"gre (B)"},
		//{"ell (T)",	"el",	"Greek, Modern (1453-)"},
		{"gre",	"el",	"Greek, Modern (1453-)"},
		{"ell",	"el",	"Greek, Modern (1453-)"},
		{"grn",	"gn",	"Guarani"},
		{"gsw",	null,	"Swiss German; Alemannic; Alsatian"},
		{"guj",	"gu",	"Gujarati"},
		{"gwi",	null,	"Gwich'in"},
		{"hai",	null,	"Haida"},
		{"hat",	"ht",	"Haitian; Haitian Creole"},
		{"hau",	"ha",	"Hausa"},
		{"haw",	null,	"Hawaiian"},
		{"heb",	"he",	"Hebrew"},
		{"her",	"hz",	"Herero"},
		{"hil",	null,	"Hiligaynon"},
		{"him",	null,	"Himachali languages; Western Pahari languages"},
		{"hin",	"hi",	"Hindi"},
		{"hit",	null,	"Hittite"},
		{"hmn",	null,	"Hmong; Mong"},
		{"hmo",	"ho",	"Hiri Motu"},
		{"hrv",	"hr",	"Croatian"},
		{"hsb",	null,	"Upper Sorbian"},
		{"hun",	"hu",	"Hungarian"},
		{"hup",	null,	"Hupa"},
		//{"arm (B)"},
		//{"hye (T)",	"hy",	"Armenian"},
		{"arm",	"hy",	"Armenian"},
		{"hye",	"hy",	"Armenian"},
		{"iba",	null,	"Iban"},
		{"ibo",	"ig",	"Igbo"},
		//{"ice (B)"},
		//{"isl (T)",	"is",	"Icelandic"},
		{"ice",	"is",	"Icelandic"},
		{"isl",	"is",	"Icelandic"},
		{"ido",	"io",	"Ido"},
		{"iii",	"ii",	"Sichuan Yi; Nuosu"},
		{"ijo",	null,	"Ijo languages"},
		{"iku",	"iu",	"Inuktitut"},
		{"ile",	"ie",	"Interlingue; Occidental"},
		{"ilo",	null,	"Iloko"},
		{"ina",	"ia",	"Interlingua (International Auxiliary Language Association)"},
		{"inc",	null,	"Indic languages"},
		{"ind",	"id",	"Indonesian"},
		{"ine",	null,	"Indo-European languages"},
		{"inh",	null,	"Ingush"},
		{"ipk",	"ik",	"Inupiaq"},
		{"ira",	null,	"Iranian languages"},
		{"iro",	null,	"Iroquoian languages"},
		//{"ice (B)"},
		//{"isl (T)",	"is",	"Icelandic"},
		{"ice",	"is",	"Icelandic"},
		{"isl",	"is",	"Icelandic"},
		{"ita",	"it",	"Italian"},
		{"jav",	"jv",	"Javanese"},
		{"jbo",	null,	"Lojban"},
		{"jpn",	"ja",	"Japanese"},
		{"jpr",	null,	"Judeo-Persian"},
		{"jrb",	null,	"Judeo-Arabic"},
		{"kaa",	null,	"Kara-Kalpak"},
		{"kab",	null,	"Kabyle"},
		{"kac",	null,	"Kachin; Jingpho"},
		{"kal",	"kl",	"Kalaallisut; Greenlandic"},
		{"kam",	null,	"Kamba"},
		{"kan",	"kn",	"Kannada"},
		{"kar",	null,	"Karen languages"},
		{"kas",	"ks",	"Kashmiri"},
		//{"geo (B)"},
		//{"kat (T)",	"ka",	"Georgian"},
		{"geo",	"ka",	"Georgian"},
		{"kat",	"ka",	"Georgian"},
		{"kau",	"kr",	"Kanuri"},
		{"kaw",	null,	"Kawi"},
		{"kaz",	"kk",	"Kazakh"},
		{"kbd",	null,	"Kabardian"},
		{"kha",	null,	"Khasi"},
		{"khi",	null,	"Khoisan languages"},
		{"khm",	"km",	"Central Khmer"},
		{"kho",	null,	"Khotanese; Sakan"},
		{"kik",	"ki",	"Kikuyu; Gikuyu"},
		{"kin",	"rw",	"Kinyarwanda"},
		{"kir",	"ky",	"Kirghiz; Kyrgyz"},
		{"kmb",	null,	"Kimbundu"},
		{"kok",	null,	"Konkani"},
		{"kom",	"kv",	"Komi"},
		{"kon",	"kg",	"Kongo"},
		{"kor",	"ko",	"Korean"},
		{"kos",	null,	"Kosraean"},
		{"kpe",	null,	"Kpelle"},
		{"krc",	null,	"Karachay-Balkar"},
		{"krl",	null,	"Karelian"},
		{"kro",	null,	"Kru languages"},
		{"kru",	null,	"Kurukh"},
		{"kua",	"kj",	"Kuanyama; Kwanyama"},
		{"kum",	null,	"Kumyk"},
		{"kur",	"ku",	"Kurdish"},
		{"kut",	null,	"Kutenai"},
		{"lad",	null,	"Ladino"},
		{"lah",	null,	"Lahnda"},
		{"lam",	null,	"Lamba"},
		{"lao",	"lo",	"Lao"},
		{"lat",	"la",	"Latin"},
		{"lav",	"lv",	"Latvian"},
		{"lez",	null,	"Lezghian"},
		{"lim",	"li",	"Limburgan; Limburger; Limburgish"},
		{"lin",	"ln",	"Lingala"},
		{"lit",	"lt",	"Lithuanian"},
		{"lol",	null,	"Mongo"},
		{"loz",	null,	"Lozi"},
		{"ltz",	"lb",	"Luxembourgish; Letzeburgesch"},
		{"lua",	null,	"Luba-Lulua"},
		{"lub",	"lu",	"Luba-Katanga"},
		{"lug",	"lg",	"Ganda"},
		{"lui",	null,	"Luiseno"},
		{"lun",	null,	"Lunda"},
		{"luo",	null,	"Luo (Kenya and Tanzania)"},
		{"lus",	null,	"Lushai"},
		//{"mac (B)"},
		//{"mkd (T)",	"mk",	"Macedonian"},
		{"mac",	"mk",	"Macedonian"},
		{"mkd",	"mk",	"Macedonian"},
		{"mad",	null,	"Madurese"},
		{"mag",	null,	"Magahi"},
		{"mah",	"mh",	"Marshallese"},
		{"mai",	null,	"Maithili"},
		{"mak",	null,	"Makasar"},
		{"mal",	"ml",	"Malayalam"},
		{"man",	null,	"Mandingo"},
		//{"mao (B)"},
		//{"mri (T)",	"mi",	"Maori"},
		{"mao",	"mi",	"Maori"},
		{"mri",	"mi",	"Maori"},
		{"map",	null,	"Austronesian languages"},
		{"mar",	"mr",	"Marathi"},
		{"mas",	null,	"Masai"},
		//{"may (B)"},
		//{"msa (T)",	"ms",	"Malay"},
		{"may",	"ms",	"Malay"},
		{"msa",	"ms",	"Malay"},
		{"mdf",	null,	"Moksha"},
		{"mdr",	null,	"Mandar"},
		{"men",	null,	"Mende"},
		{"mga",	null,	"Irish, Middle (900-1200)"},
		{"mic",	null,	"Mi'kmaq; Micmac"},
		{"min",	null,	"Minangkabau"},
		{"mis",	null,	"Uncoded languages"},
		//{"mac (B)"},
		//{"mkd (T)",	"mk",	"Macedonian"},
		{"mac",	"mk",	"Macedonian"},
		{"mkd",	"mk",	"Macedonian"},
		{"mkh",	null,	"Mon-Khmer languages"},
		{"mlg",	"mg",	"Malagasy"},
		{"mlt",	"mt",	"Maltese"},
		{"mnc",	null,	"Manchu"},
		{"mni",	null,	"Manipuri"},
		{"mno",	null,	"Manobo languages"},
		{"moh",	null,	"Mohawk"},
		{"mon",	"mn",	"Mongolian"},
		{"mos",	null,	"Mossi"},
		//{"mao (B)"},
		//{"mri (T)",	"mi",	"Maori"},
		{"mao",	"mi",	"Maori"},
		{"mri",	"mi",	"Maori"},
		//{"may (B)"},
		//{"msa (T)",	"ms",	"Malay"},
		{"may",	"ms",	"Malay"},
		{"msa",	"ms",	"Malay"},
		{"mul",	null,	"Multiple languages"},
		{"mun",	null,	"Munda languages"},
		{"mus",	null,	"Creek"},
		{"mwl",	null,	"Mirandese"},
		{"mwr",	null,	"Marwari"},
		//{"bur (B)"},
		//{"mya (T)",	"my",	"Burmese"},
		{"bur",	"my",	"Burmese"},
		{"mya",	"my",	"Burmese"},
		{"myn",	null,	"Mayan languages"},
		{"myv",	null,	"Erzya"},
		{"nah",	null,	"Nahuatl languages"},
		{"nai",	null,	"North American Indian languages"},
		{"nap",	null,	"Neapolitan"},
		{"nau",	"na",	"Nauru"},
		{"nav",	"nv",	"Navajo; Navaho"},
		{"nbl",	"nr",	"Ndebele, South; South Ndebele"},
		{"nde",	"nd",	"Ndebele, North; North Ndebele"},
		{"ndo",	"ng",	"Ndonga"},
		{"nds",	null,	"Low German; Low Saxon; German, Low; Saxon, Low"},
		{"nep",	"ne",	"Nepali"},
		{"new",	null,	"Nepal Bhasa; Newari"},
		{"nia",	null,	"Nias"},
		{"nic",	null,	"Niger-Kordofanian languages"},
		{"niu",	null,	"Niuean"},
		//{"dut (B)"},
		//{"nld (T)",	"nl",	"Dutch; Flemish"},
		{"dut",	"nl",	"Dutch; Flemish"},
		{"nld",	"nl",	"Dutch; Flemish"},
		{"nno",	"nn",	"Norwegian Nynorsk; Nynorsk, Norwegian"},
		{"nob",	"nb",	"Bokmål, Norwegian; Norwegian Bokmål"},
		{"nog",	null,	"Nogai"},
		{"non",	null,	"Norse, Old"},
		{"nor",	"no",	"Norwegian"},
		{"nqo",	null,	"N'Ko"},
		{"nso",	null,	"Pedi; Sepedi; Northern Sotho"},
		{"nub",	null,	"Nubian languages"},
		{"nwc",	null,	"Classical Newari; Old Newari; Classical Nepal Bhasa"},
		{"nya",	"ny",	"Chichewa; Chewa; Nyanja"},
		{"nym",	null,	"Nyamwezi"},
		{"nyn",	null,	"Nyankole"},
		{"nyo",	null,	"Nyoro"},
		{"nzi",	null,	"Nzima"},
		{"oci",	"oc",	"Occitan (post 1500)"},
		{"oji",	"oj",	"Ojibwa"},
		{"ori",	"or",	"Oriya"},
		{"orm",	"om",	"Oromo"},
		{"osa",	null,	"Osage"},
		{"oss",	"os",	"Ossetian; Ossetic"},
		{"ota",	null,	"Turkish, Ottoman (1500-1928)"},
		{"oto",	null,	"Otomian languages"},
		{"paa",	null,	"Papuan languages"},
		{"pag",	null,	"Pangasinan"},
		{"pal",	null,	"Pahlavi"},
		{"pam",	null,	"Pampanga; Kapampangan"},
		{"pan",	"pa",	"Panjabi; Punjabi"},
		{"pap",	null,	"Papiamento"},
		{"pau",	null,	"Palauan"},
		{"peo",	null,	"Persian, Old (ca.600-400 B.C.)"},
		//{"per (B)"},
		//{"fas (T)",	"fa",	"Persian"},
		{"per",	"fa",	"Persian"},
		{"fas",	"fa",	"Persian"},
		{"phi",	null,	"Philippine languages"},
		{"phn",	null,	"Phoenician"},
		{"pli",	"pi",	"Pali"},
		{"pol",	"pl",	"Polish"},
		{"pon",	null,	"Pohnpeian"},
		{"por",	"pt",	"Portuguese"},
		{"pra",	null,	"Prakrit languages"},
		{"pro",	null,	"Provençal, Old (to 1500);Occitan, Old (to 1500)"},
		{"pus",	"ps",	"Pushto; Pashto"},
		{"qaa-qtz",	null,	"Reserved for local use"},
		{"que",	"qu",	"Quechua"},
		{"raj",	null,	"Rajasthani"},
		{"rap",	null,	"Rapanui"},
		{"rar",	null,	"Rarotongan; Cook Islands Maori"},
		{"roa",	null,	"Romance languages"},
		{"roh",	"rm",	"Romansh"},
		{"rom",	null,	"Romany"},
		//{"rum (B)"},
		//{"ron (T)",	"ro",	"Romanian; Moldavian; Moldovan"},
		{"rum",	"ro",	"Romanian; Moldavian; Moldovan"},
		{"ron",	"ro",	"Romanian; Moldavian; Moldovan"},
		//{"rum (B)"},
		//{"ron (T)",	"ro",	"Romanian; Moldavian; Moldovan"},
		{"rum",	"ro",	"Romanian; Moldavian; Moldovan"},
		{"ron",	"ro",	"Romanian; Moldavian; Moldovan"},
		{"run",	"rn",	"Rundi"},
		{"rup",	null,	"Aromanian; Arumanian; Macedo-Romanian"},
		{"rus",	"ru",	"Russian"},
		{"sad",	null,	"Sandawe"},
		{"sag",	"sg",	"Sango"},
		{"sah",	null,	"Yakut"},
		{"sai",	null,	"South American Indian languages"},
		{"sal",	null,	"Salishan languages"},
		{"sam",	null,	"Samaritan Aramaic"},
		{"san",	"sa",	"Sanskrit"},
		{"sas",	null,	"Sasak"},
		{"sat",	null,	"Santali"},
		{"scn",	null,	"Sicilian"},
		{"sco",	null,	"Scots"},
		{"sel",	null,	"Selkup"},
		{"sem",	null,	"Semitic languages"},
		{"sga",	null,	"Irish, Old (to 900)"},
		{"sgn",	null,	"Sign Languages"},
		{"shn",	null,	"Shan"},
		{"sid",	null,	"Sidamo"},
		{"sin",	"si",	"Sinhala; Sinhalese"},
		{"sio",	null,	"Siouan languages"},
		{"sit",	null,	"Sino-Tibetan languages"},
		{"sla",	null,	"Slavic languages"},
		//{"slo (B)"},
		//{"slk (T)",	"sk",	"Slovak"},
		{"slo",	"sk",	"Slovak"},
		{"slk",	"sk",	"Slovak"},
		//{"slo (B)"},
		//{"slk (T)",	"sk",	"Slovak"},
		{"slo",	"sk",	"Slovak"},
		{"slk",	"sk",	"Slovak"},
		{"slv",	"sl",	"Slovenian"},
		{"sma",	null,	"Southern Sami"},
		{"sme",	"se",	"Northern Sami"},
		{"smi",	null,	"Sami languages"},
		{"smj",	null,	"Lule Sami"},
		{"smn",	null,	"Inari Sami"},
		{"smo",	"sm",	"Samoan"},
		{"sms",	null,	"Skolt Sami"},
		{"sna",	"sn",	"Shona"},
		{"snd",	"sd",	"Sindhi"},
		{"snk",	null,	"Soninke"},
		{"sog",	null,	"Sogdian"},
		{"som",	"so",	"Somali"},
		{"son",	null,	"Songhai languages"},
		{"sot",	"st",	"Sotho, Southern"},
		{"spa",	"es",	"Spanish; Castilian"},
		//{"alb (B)"},
		//{"sqi (T)",	"sq",	"Albanian"},
		{"alb",	"sq",	"Albanian"},
		{"sqi",	"sq",	"Albanian"},
		{"srd",	"sc",	"Sardinian"},
		{"srn",	null,	"Sranan Tongo"},
		{"srp",	"sr",	"Serbian"},
		{"srr",	null,	"Serer"},
		{"ssa",	null,	"Nilo-Saharan languages"},
		{"ssw",	"ss",	"Swati"},
		{"suk",	null,	"Sukuma"},
		{"sun",	"su",	"Sundanese"},
		{"sus",	null,	"Susu"},
		{"sux",	null,	"Sumerian"},
		{"swa",	"sw",	"Swahili"},
		{"swe",	"sv",	"Swedish"},
		{"syc",	null,	"Classical Syriac"},
		{"syr",	null,	"Syriac"},
		{"tah",	"ty",	"Tahitian"},
		{"tai",	null,	"Tai languages"},
		{"tam",	"ta",	"Tamil"},
		{"tat",	"tt",	"Tatar"},
		{"tel",	"te",	"Telugu"},
		{"tem",	null,	"Timne"},
		{"ter",	null,	"Tereno"},
		{"tet",	null,	"Tetum"},
		{"tgk",	"tg",	"Tajik"},
		{"tgl",	"tl",	"Tagalog"},
		{"tha",	"th",	"Thai"},
		//{"tib (B)"},
		//{"bod (T)",	"bo",	"Tibetan"},
		{"tib",	"bo",	"Tibetan"},
		{"bod",	"bo",	"Tibetan"},
		{"tig",	null,	"Tigre"},
		{"tir",	"ti",	"Tigrinya"},
		{"tiv",	null,	"Tiv"},
		{"tkl",	null,	"Tokelau"},
		{"tlh",	null,	"Klingon; tlhIngan-Hol"},
		{"tli",	null,	"Tlingit"},
		{"tmh",	null,	"Tamashek"},
		{"tog",	null,	"Tonga (Nyasa)"},
		{"ton",	"to",	"Tonga (Tonga Islands)"},
		{"tpi",	null,	"Tok Pisin"},
		{"tsi",	null,	"Tsimshian"},
		{"tsn",	"tn",	"Tswana"},
		{"tso",	"ts",	"Tsonga"},
		{"tuk",	"tk",	"Turkmen"},
		{"tum",	null,	"Tumbuka"},
		{"tup",	null,	"Tupi languages"},
		{"tur",	"tr",	"Turkish"},
		{"tut",	null,	"Altaic languages"},
		{"tvl",	null,	"Tuvalu"},
		{"twi",	"tw",	"Twi"},
		{"tyv",	null,	"Tuvinian"},
		{"udm",	null,	"Udmurt"},
		{"uga",	null,	"Ugaritic"},
		{"uig",	"ug",	"Uighur; Uyghur"},
		{"ukr",	"uk",	"Ukrainian"},
		{"umb",	null,	"Umbundu"},
		{"und",	null,	"Undetermined"},
		{"urd",	"ur",	"Urdu"},
		{"uzb",	"uz",	"Uzbek"},
		{"vai",	null,	"Vai"},
		{"ven",	"ve",	"Venda"},
		{"vie",	"vi",	"Vietnamese"},
		{"vol",	"vo",	"Volapük"},
		{"vot",	null,	"Votic"},
		{"wak",	null,	"Wakashan languages"},
		{"wal",	null,	"Wolaitta; Wolaytta"},
		{"war",	null,	"Waray"},
		{"was",	null,	"Washo"},
		//{"wel (B)"},
		//{"cym (T)",	"cy",	"Welsh"},
		{"wel",	"cy",	"Welsh"},
		{"cym",	"cy",	"Welsh"},
		{"wen",	null,	"Sorbian languages"},
		{"wln",	"wa",	"Walloon"},
		{"wol",	"wo",	"Wolof"},
		{"xal",	null,	"Kalmyk; Oirat"},
		{"xho",	"xh",	"Xhosa"},
		{"yao",	null,	"Yao"},
		{"yap",	null,	"Yapese"},
		{"yid",	"yi",	"Yiddish"},
		{"yor",	"yo",	"Yoruba"},
		{"ypk",	null,	"Yupik languages"},
		{"zap",	null,	"Zapotec"},
		{"zbl",	null,	"Blissymbols; Blissymbolics; Bliss"},
		{"zen",	null,	"Zenaga"},
		{"zha",	"za",	"Zhuang; Chuang"},
		//{"chi (B)"},
		//{"zho (T)",	"zh",	"Chinese"},
		{"chi",	"zh",	"Chinese"},
		{"zho",	"zh",	"Chinese"},
		{"znd",	null,	"Zande languages"},
		{"zul",	"zu",	"Zulu"},
		{"zun",	null,	"Zuni"},
		{"zxx",	null,	"No linguistic content; Not applicable"},
		{"zza",	null,	"Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"}
	};
	
}
